Repository MrAnonymous09/hactoberfest-non-coding-contribution, pull requests merged in 2022-10, with the labels that each got.

#14 Create README.md
  Annapurna/README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#16 My Photography
  PIC_1.jpeg
  PIC_2.jpeg
Labels: hacktoberfest-accepted

#7 Update README.md
  Neeraj Singh/README.md
Labels: invalid, spam
